services:
  mysql-progress:
    image: mysql:8.0.22
    container_name: my-mysql-progress-tracker
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kafka-network


networks:
  kafka-network:
    external: true
