services:
  mysql-progress:
    image: mysql:8.0.22
    container_name: my-mysql-progress-tracker
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user_progress_tracker
      MYSQL_PASSWORD: progress_trackerPW
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: progress_tracker
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
